name: Build

on:
  - push
  - pull_request

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Dump context
      env:
        CONTEXT: ${{ toJson(github) }}
      run: |
        echo "Context: $CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100-preview.4.20258.7'

    - name: Build
      run: |
        dotnet build --configuration Release
        dotnet test --configuration Release --no-build
        dotnet pack --configuration Release --no-build
